name: 'Authenticate to an environment or a sandbox created by DevHub User'
description: 'Authenticate to an environment or a sandbox created by DevHub User'

inputs:
  DEVHUB_SFDX_AUTH_URL:
    description: "Auth URL to DEVHUB"
    required: true
  SB_SFDX_AUTH_URL:
    description: "Auth URL to Sandbox"
    required: false
  environment:
    description: "Environment to authenticate to"
    required: false
  environment-profile:
    description: "Environment profile to use"
    required: false
  org-name:
    description: "Name of the sandbox in case of non env sandbox"
    required: false
outputs:
  alias:
    description: 'Name of the sandbox'
    value: ${{ steps.handle-auth.outputs.alias }}


runs:
  using: "composite"
  steps:
      - name: Authenticate to ${{ inputs.environment }}3
        id: handle-auth
        shell: bash
        run: |

              #No matter what authenticate devhub
              echo "${{ inputs.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
              sfdx auth:sfdxurl:store -f ./authfile -a prod
              devhubInfo=$(sf org display -o prod --json)
              DEVHUB_USERNAME=$(echo $devhubInfo | jq -r '.result.username')
              echo "devhub_username=$DEVHUB_USERNAME" >> "$GITHUB_OUTPUT"


              if [[ "${{ inputs.org-name  }}" == "prod"  || "${{ inputs.environment }}" == "prod" ]]
              then
                # set an alias to prod
                if [[ "${{ inputs.org-name  }}" == "prod" ]]
                then
                  echo "alias=${{ inputs.org-name }}" >> "$GITHUB_OUTPUT"
                else
                  echo "alias=${{ inputs.environment }}" >> "$GITHUB_OUTPUT"
                fi
              elif [[ "${{ inputs.SB_SFDX_AUTH_URL }}" != '' ]]
              then
                echo "${{ inputs.SB_SFDX_AUTH_URL }}" > ./authfile
                sfdx auth:sfdxurl:store -f ./authfile -a ${{ inputs.environment }}
                echo "alias=${{ inputs.environment }}" >> "$GITHUB_OUTPUT"
              else
                echo "No Auth URL found for ${{ inputs.org-name }},Attempting to login assuming the devhub user  created enviroment"
                sf org sandbox resume -n ${{ inputs.org-name }} -o prod
                SBX_NAME=$(echo "${{ inputs.org-name }}" | sed -e 's/^ *//' -e 's/ *$//')
                sf alias set ${{ inputs.environment-profile }}=$DEVHUB_USERNAME.$SBX_NAME
                echo "alias=${{ inputs.environment-profile }}" >> "$GITHUB_OUTPUT"
              fi