#always assume it needs sfpowerscripts docker image as the run time

name: "Report status of scratchOrgs"
description: "Report status of scratchOrgs"
inputs:
  devhub_sfdx_auth_url:
    description: "Devhub SFDX Auth URL"
    required: true
  dashboard-repo:
    description: "name of the repo to report to, will create a folder packageVersionReports in the target repo"
    required: true
  gh_token:
    description: "github token to use for commiting to repo"
    required: true

runs:
  using: "composite"
  steps:
    # Set up GH_TOKEN on the environment as secret doesnt seem to pass onto other action
    - run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        export GH_TOKEN=${{inputs.gh_token}}
        echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV
      shell: bash


    - run: |
        echo "${{ inputs.devhub_sfdx_auth_url }}" > ./authfile
        sfdx auth:sfdxurl:store -f authfile -a devhub
      shell: bash

    - run: |
        mkdir -p _data/scratchOrgStatus
        node $GITHUB_ACTION_PATH/retrieveStatus.js devhub ${{github.repository}} _data/scratchOrgStatus/scratchOrgStatus.json
      shell: bash

    - name: "Push changes to dashboard-repo"
      id: updateGitRepo
      uses: flxbl-io/sfops-gh-actions/updateGitRepo@main
      with:
        target-repo: ${{ inputs.dashboard-repo }}
        source-dir: _data
        target-dir: _data
        commit-message: "Updated information about scratchorgs"
        update-release-names: false
        gh_token: ${{ inputs.gh_token }}
