name: 'Figure out impacted release defns'
description: 'Figures out impacted release defns based on git diff'
inputs:
  pathToReleaseDefns:
    description: 'The path to the directory that contains release defns'
    required: true
  from-commit:
    description: 'The commit id from where changes should be analyzed'
    required: true
  to-commit:
    description: 'The commit id to which changes should be analyzed'
    required: true


runs:
  using: "composite"
  steps:
    - run: |
         node $GITHUB_ACTION_PATH/dist/index.js ${{inputs.pathToReleaseDefns}} ${{inputs.from-commit}} ${{inputs.to-commit}}
      shell: bash
      id: computeImpactedReleaseDefns


