#always assume it needs sfpowerscripts docker image as the run time

name: "Report status of sandboxes"
description: "Report status of sandbox"
inputs:
  dashboard-repo:
    description: "name of the repo to report to, will create a folder packageVersionReports in the target repo"
    required: true
  gh_token:
    description: "github token to use for commiting to repo"
    required: true

runs:
  using: "composite"
  steps:
    # Set up GH_TOKEN on the environment as secret doesnt seem to pass onto other action
    - run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        export GH_TOKEN=${{inputs.gh_token}}
        echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV
      shell: bash

    - run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        mkdir -p _data/sandboxStatus

        node $GITHUB_ACTION_PATH/sandboxStatus.js ${{ github.repository }}

        if [ -f developer_sandboxes.json ]; then
         cp -f developer_sandboxes.json _data/sandboxStatus/developerSandboxes.json
        fi

        if [ -f developer_sandboxes.json ]; then
         cp -f ci_sandboxes.json _data/sandboxStatus/ciSandboxes.json
        fi

      shell: bash

    - name: "Push changes to dashboard-repo"
      id: updateGitRepo
      uses: flxbl-io/sfops-gh-actions/updateGitRepo@main
      with:
        target-repo: ${{ inputs.dashboard-repo }}
        source-dir: _data
        target-dir: _data
        commit-message: "Updated information about a branch"
        update-release-names: false
        gh_token: ${{ inputs.gh_token }}
