name: "Remove an existing assignment on pool"
description: "Expire an exiting issue assigned sandbox, so user can fetch a new one"
inputs:
  pool:
    description: "The pool name"
    required: true
  branch:
    description: "The branch of the sandbox pool"
    required: true
  issue-number:
     description: "The issue number where this sandbox will be used"
     required: true
  gh_token: # id of input
    description: "github token to use for commiting to repo"
    required: true
outputs:
  sbxname:
    description: "Name of the sandbox"
    value: ${{ steps.removeAsssignment.outputs.SANDBOX_NAME }}
runs:
  using: "composite"
  steps:
    # Set up GH_TOKEN on the environment as secret doesnt seem to pass onto other action
    - run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        export GH_TOKEN=${{inputs.gh_token}}
        echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV
      shell: bash

    - name: Lock to get exclusive access to pool var
      uses: flxbl-io/sfops-gh-actions/lockResource@main
      id: lockResource
      with:
        branch: pool-${{inputs.pool}}-${{inputs.branch}}
        repo-token: ${{ inputs.gh_token }}

    - run: |
        export GH_TOKEN=${{inputs.gh_token}}
        sbx_name=$(node $GITHUB_ACTION_PATH/removeAsssignment.js  ${{github.repository}} ${{inputs.pool}}  ${{inputs.branch}} ${{ inputs.issue-number }} 20 )
        echo "SANDBOX_NAME=$sbx_name" >> "$GITHUB_OUTPUT"
      shell: bash
      id: removeAsssignment

    - name: Release locked access to pool vars
      uses: flxbl-io/sfops-gh-actions/unlockResource@main
      if: always()
      with:
        branch: pool-${{inputs.pool}}-${{inputs.branch}}
        repo-token: ${{ inputs.gh_token }}
        ticket_id: ${{ steps.lockResource.outputs.ticket_id }}
