name: 'Changelog to Html Reporter'
description: 'Convert changelog.json to html and commit to repo'
inputs:
  source-branch: 
    description: 'name of the branch from which to read changelog.json'
    required: true
  target-dir: 
    description: 'name of the directory to commit to'
    required: true
  target-repo:  
    description: 'name of the repo to report to, will create a folder release-pipeline-view in the target repo'
    required: true
  workitem-url:
     description: 'url of the jira board'
     required: true
  source-repo-url:
      description: 'url of the source repo'
      required: true
  pathToReleaseConfigs:
      description: 'The directory that has all release config'
  gh_token:
    description: 'github token to use for committing to repo'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
          # Install gh cli on ubuntu
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y                
      shell: bash

    - name: 'Fetch all ReleaseNames'
      id: getAllReleaseNames
      uses: flxbl-io/sfops-gh-actions/fetchAllReleaseNames@main  
      with:
          pathToReleaseConfigs: ${{ inputs.pathToReleaseConfigs}}
    
    - run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git fetch --all
          mkdir -p changelogHTML
          export GH_TOKEN=${{inputs.gh_token}}
          IFS=',' read -ra DOMAIN_ARRAY <<< "${{steps.getAllReleaseNames.outputs.releaseNames}}"
          for domain in "${DOMAIN_ARRAY[@]}"; do
            git show origin/${{inputs.source-branch}}:${domain}/releasechangelog.json > releasechangelog.json
            node  $GITHUB_ACTION_PATH/changelogToHTML.js releasechangelog.json ${{inputs.workitem-url}} ${{inputs.source-repo-url}} $domain
            cp changelog-${domain}.html changelogHTML
          done
          $GITHUB_ACTION_PATH/git-repo-commiter.sh ${{inputs.target-repo}} changelogHTML ${{inputs.target-dir}} "updated changelog for domains ${{inputs.domains}}"
      shell: bash
