name: 'Fetch all release names'
description: 'Fetch all release names given a path to the directory that contains release defns'
inputs:
  pathToReleaseConfigs:
    description: 'The path to the directory that contains release defns'
    required: true
    default: 'config'
outputs:
   releaseNames:
    description: 'The impacted release defns'
    value: ${{ steps.getAllReleaseNames.outputs.releaseNames }}


runs:
  using: "composite"
  steps:
    - run: |
         releaseNamesAsJSONArray=$(node $GITHUB_ACTION_PATH/dist/index.js ${{inputs.pathToReleaseConfigs}})
         releaseNames=$(echo $releaseNamesAsJSONArray | tr -d '[]' | sed "s/'//g")
         echo "releaseNames=$releaseNames" >> "GITHUB_OUTPUT"
      shell: bash
      id: getAllReleaseNames


