name: "Check a CI Sandbox Status"
description: "Check a status of CI Sandbox and add to the pool if ready, Also deactivate all other users"

inputs:
  devhub_sfdx_auth_url:
    description: "Devhub SFDX Auth URL"
    required: true
  usersToBeActivated:
    description: "Comma separated list of users to be activated"
    required: true
  pathToPoolConfigFile:
    description: "Path to pool config file"
    required: true
  gh_token:
    description: "GitHub Token"
    required: true
  metrics-provider:
    description: "The metrics provider to be used"
  DATADOG_API_KEY:
    description: "Datadog api key to report metrics"
  DATADOG_HOST:
    description: "Datadog host to report metrics"

runs:
  using: "composite"
  steps:
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      shell: bash

    - run: |
        echo "${{ inputs.devhub_sfdx_auth_url }}" > ./authfile
        sfdx auth:sfdxurl:store -f authfile -a devhub
      shell: bash

    - id: checkSandboxStatus
      run: |
        devhubInfo=$(sf org display -o devhub --json)
        DEVHUB_USERNAME=$(echo $devhubInfo | jq -r '.result.username')
        export GH_TOKEN=${{inputs.gh_token}}

        if [ '${{ inputs.metrics-provider }}' = 'datadog' ]; then
         export "SFPOWERSCRIPTS_DATADOG=true" 
         export "SFPOWERSCRIPTS_DATADOG_HOST=${{ inputs.DATADOG_HOST }}"
         export "SFPOWERSCRIPTS_DATADOG_API_KEY=${{ inputs.DATADOG_API_KEY }}"
        fi

        node $GITHUB_ACTION_PATH/checkSandboxStatus.js  ${{ inputs.gh_token }}  $GITHUB_ACTION_PATH   ${{ github.repository_owner }} ${{ github.event.repository.name }}   $DEVHUB_USERNAME ${{ inputs.pathToPoolConfigFile }}
        node $GITHUB_ACTION_PATH/expireOldSandboxes.js  ${{ github.repository }} ${{ inputs.pathToPoolConfigFile }}
      shell: bash