name: 'Freeze all users in a provided org'
description: 'Freeze users in a provided org'
inputs:
  profiles:
    description: 'Name of the profiles to be excluded from from frozen, by default only System Adminstrator profile is excluded'
    required: true
  target-org-alias:
    description: 'Alias of the target org from which the users will be frozen'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        node $GITHUB_ACTION_PATH/dist/index.js  ${{ inputs.target-org-alias }}  ${{ inputs.profiles }}
      shell: bash
